export const LIGHT_THEME = "light";
export const DARK_THEME = "dark";

export const projects = [
  {
    id: 1,
    title: "Portfolio Website",
    description:
      "Showcase of my projects, skills, and experience as a developer",
    technologies: [
      "Next.js",
      "React.js",
      "react-spring",
      "Framer Motion",
      "Styled Components",
      "Lucide-react",
      "react-intersection-observer",
    ],
    category: "Front end",
    year: "2025",
    status: "Live",
    metrics: { users: "More than 1", conversion: "Good", performance: "90" },
    link: "https://github.com/devraghul/portfolio/tree/main",
    demo: "https://devraghul.github.io/portfolio/",
    color: "#ff6b35",
  },
  {
    id: 2,
    title: "Flipkart Clone",
    description:
      "E-commerce platform with real-time collaboration and advanced search capabilities",
    technologies: [
      "React.js",
      "Node.js",
      "Express.js",
      "GraphQL",
      "MongoDB",
      "Netlify",
      "Heroku",
    ],
    category: "SaaS",
    year: "2023",
    status: "Beta",
    metrics: {
      teams: "My friends",
      efficiency: "70%",
      uptime: "Whenever we needed",
    },
    link: "https://github.com/devraghul/Ecart_frontend_React",
    demo: "https://devraghul.github.io/Ecart_frontend_React/",
    color: "#4ecdc4",
  },
  {
    id: 3,
    title: "JSON Vault",
    description: "Secure JSON storage and management system with encryption",
    technologies: [
      "Node.js",
      "Express.js",
      "HTML",
      "CSS",
      "JavaScript",
      "Render",
    ],
    category: "SaaS",
    year: "2025",
    status: "Live",
    metrics: { accuracy: "99%", data: "Dynamic", version: "1" },
    link: "https://github.com/devraghul/jsonvault",
    demo: "https://jsonvault-cy79.onrender.com/",
    color: "#45b7d1",
  },
  {
    id: 4,
    title: "Planner",
    description:
      "Decentralized task planner without internet to remember tasks",
    technologies: ["HTML", "CSS", "JavaScript"],
    category: "SaaS",
    year: "2021",
    status: "Live",
    metrics: { accuracy: "99%", data: "Local", version: "2" },
    link: "https://github.com/devraghul/Planner",
    demo: "https://devraghul.github.io/Planner/",
    color: "#f39c12",
  },
];
